repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0  # Актуальная версия Black
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4  # Актуальная версия Ruff
    hooks:
      - id: ruff
      - id: ruff-format